/* eslint-disable import/no-unresolved */
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from '../build/server';
import { als } from '~/async-storage.server';

let test = 0;

export const onRequest: PagesFunction<Env> = async (context) => {
  const rayId = context.request.headers.get('cf-ray');

  const res = await als().run(
    {
      rayId,
      test: test++,
    },
    async () => {
      // console.log(getTest());

      const res = await createPagesFunctionHandler({ build })(context);

      return res;
    }
  );

  return res;
};
