// Generated by Wrangler on Wed Apr 10 2024 17:25:38 GMT+0300 (Moscow Standard Time)
// by running `wrangler types`

interface Env {
	MY_VARIABLE: "lcoal_value";
	DEV_MODE_DATABASE_URL: "postgresql://user:pass@localhost:5432/webstudio";
	MY_SECRET: string;
	HYPERDRIVE: Hyperdrive;
}
