name: Execute Public Repo Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: olegisonen/webstudio:main

    steps:
      - uses: actions/checkout@v2

      - name: Execute a step from a public repo
        run: |
          echo "Hello, world!"
          echo "This is a step from a public repo"
          ls -la /
